version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: music_school
    restart: always
    environment:
      POSTGRES_USER: musicschool
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: musicschooldb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: